#!/usr/bin/env bash
set -euo pipefail

# Deploy contracts to a local Anvil devnet and write addresses to .env.deployed
#
# Usage: ./ops/deploy.sh [RPC_URL]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT_DIR/contracts"
ENV_FILE="$SCRIPT_DIR/.env.deployed"

RPC_URL="${1:-http://127.0.0.1:8545}"
DATABASE_URL="${DATABASE_URL:-postgres://localhost:5432/ai_chain}"

# Anvil account 0 — deployer
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

echo "==> Deploying contracts to $RPC_URL"

# Wait for RPC to be available
for i in $(seq 1 30); do
  if cast block-number --rpc-url "$RPC_URL" &>/dev/null; then
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "ERROR: RPC at $RPC_URL not reachable after 30 seconds"
    exit 1
  fi
  sleep 1
done

# Deploy via forge script
cd "$CONTRACTS_DIR"
forge script script/Deploy.s.sol \
  --rpc-url "$RPC_URL" \
  --private-key "$DEPLOYER_KEY" \
  --broadcast \
  --quiet

# Parse deployed addresses from broadcast JSON
CHAIN_ID=$(cast chain-id --rpc-url "$RPC_URL")
BROADCAST_FILE="$CONTRACTS_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"

if [ ! -f "$BROADCAST_FILE" ]; then
  echo "ERROR: Broadcast file not found at $BROADCAST_FILE"
  exit 1
fi

# Extract contract addresses in deployment order
# Deploy.s.sol creates: AgentRegistry, IntentBook, PolicyModule, AttestationRegistry
AGENT_REGISTRY=$(jq -r '.transactions[0].contractAddress' "$BROADCAST_FILE")
INTENT_BOOK=$(jq -r '.transactions[1].contractAddress' "$BROADCAST_FILE")
POLICY_MODULE=$(jq -r '.transactions[2].contractAddress' "$BROADCAST_FILE")
ATTESTATION_REGISTRY=$(jq -r '.transactions[3].contractAddress' "$BROADCAST_FILE")

echo "    AgentRegistry:        $AGENT_REGISTRY"
echo "    IntentBook:           $INTENT_BOOK"
echo "    PolicyModule:         $POLICY_MODULE"
echo "    AttestationRegistry:  $ATTESTATION_REGISTRY"

# Write .env.deployed for services and demo
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — do not edit
RPC_URL=$RPC_URL
DATABASE_URL=$DATABASE_URL
AGENT_REGISTRY_ADDRESS=$AGENT_REGISTRY
INTENT_BOOK_ADDRESS=$INTENT_BOOK
POLICY_MODULE_ADDRESS=$POLICY_MODULE
ATTESTATION_REGISTRY_ADDRESS=$ATTESTATION_REGISTRY

# Anvil account 0 — deployer
DEPLOYER_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
DEPLOYER_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

# Anvil account 1 — solver
SOLVER_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
SOLVER_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8

# Anvil account 2 — demo agent
AGENT_PRIVATE_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
AGENT_ADDRESS=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
EOF

echo "==> Addresses written to $ENV_FILE"
