#!/usr/bin/env bash
set -euo pipefail

# Deploy contracts to a public testnet and write addresses to .env.testnet
#
# Required env vars:
#   DEPLOYER_KEY        — private key of the deploying wallet (must have testnet ETH)
#
# Optional env vars:
#   RPC_URL             — defaults to Base Sepolia (https://sepolia.base.org)
#   DATABASE_URL        — Postgres connection string
#   SOLVER_PRIVATE_KEY  — solver wallet private key
#   AGENT_PRIVATE_KEY   — demo agent wallet private key
#
# Usage:
#   export DEPLOYER_KEY=0x...
#   ./ops/deploy-testnet.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT_DIR/contracts"
ENV_FILE="$SCRIPT_DIR/.env.testnet"

RPC_URL="${RPC_URL:-https://sepolia.base.org}"
DATABASE_URL="${DATABASE_URL:-}"
SOLVER_PRIVATE_KEY="${SOLVER_PRIVATE_KEY:-}"
AGENT_PRIVATE_KEY="${AGENT_PRIVATE_KEY:-}"

# --- Validate required env vars ---

if [ -z "${DEPLOYER_KEY:-}" ]; then
  echo "ERROR: DEPLOYER_KEY is required. Export it before running this script."
  echo ""
  echo "  export DEPLOYER_KEY=0x<your-deployer-private-key>"
  echo "  ./ops/deploy-testnet.sh"
  exit 1
fi

echo "==> Deploying contracts to $RPC_URL"

# Wait for RPC to be available
for i in $(seq 1 30); do
  if cast block-number --rpc-url "$RPC_URL" &>/dev/null; then
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "ERROR: RPC at $RPC_URL not reachable after 30 seconds"
    exit 1
  fi
  sleep 1
done

CHAIN_ID=$(cast chain-id --rpc-url "$RPC_URL")
echo "    Chain ID: $CHAIN_ID"

# Check deployer balance
DEPLOYER_ADDRESS=$(cast wallet address "$DEPLOYER_KEY")
BALANCE=$(cast balance "$DEPLOYER_ADDRESS" --rpc-url "$RPC_URL")
echo "    Deployer: $DEPLOYER_ADDRESS"
echo "    Balance:  $BALANCE wei"

if [ "$BALANCE" = "0" ]; then
  echo "ERROR: Deployer wallet has zero balance. Get testnet ETH from a faucet first."
  echo ""
  echo "  Base Sepolia faucets:"
  echo "    https://www.alchemy.com/faucets/base-sepolia"
  echo "    https://portal.cdp.coinbase.com/products/faucet"
  echo "    https://thirdweb.com/base-sepolia-testnet"
  exit 1
fi

# Deploy via forge script
cd "$CONTRACTS_DIR"
forge script script/Deploy.s.sol \
  --rpc-url "$RPC_URL" \
  --private-key "$DEPLOYER_KEY" \
  --broadcast

# Parse deployed addresses from broadcast JSON
BROADCAST_FILE="$CONTRACTS_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"

if [ ! -f "$BROADCAST_FILE" ]; then
  echo "ERROR: Broadcast file not found at $BROADCAST_FILE"
  exit 1
fi

# Extract contract addresses in deployment order
# Deploy.s.sol creates: AgentRegistry, IntentBook, PolicyModule, AttestationRegistry
AGENT_REGISTRY=$(jq -r '.transactions[0].contractAddress' "$BROADCAST_FILE")
INTENT_BOOK=$(jq -r '.transactions[1].contractAddress' "$BROADCAST_FILE")
POLICY_MODULE=$(jq -r '.transactions[2].contractAddress' "$BROADCAST_FILE")
ATTESTATION_REGISTRY=$(jq -r '.transactions[3].contractAddress' "$BROADCAST_FILE")

echo ""
echo "==> Deployed contracts:"
echo "    AgentRegistry:        $AGENT_REGISTRY"
echo "    IntentBook:           $INTENT_BOOK"
echo "    PolicyModule:         $POLICY_MODULE"
echo "    AttestationRegistry:  $ATTESTATION_REGISTRY"

# Write .env.testnet — references env vars for secrets, stores addresses directly
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-testnet.sh — do not edit
# Chain: $RPC_URL (chain ID $CHAIN_ID)

RPC_URL=$RPC_URL
CHAIN_ID=$CHAIN_ID
DATABASE_URL=$DATABASE_URL

# Contract addresses
AGENT_REGISTRY_ADDRESS=$AGENT_REGISTRY
INTENT_BOOK_ADDRESS=$INTENT_BOOK
POLICY_MODULE_ADDRESS=$POLICY_MODULE
ATTESTATION_REGISTRY_ADDRESS=$ATTESTATION_REGISTRY

# Deployer
DEPLOYER_ADDRESS=$DEPLOYER_ADDRESS

# Solver — set SOLVER_PRIVATE_KEY in your environment
SOLVER_PRIVATE_KEY=$SOLVER_PRIVATE_KEY

# Agent — set AGENT_PRIVATE_KEY in your environment
AGENT_PRIVATE_KEY=$AGENT_PRIVATE_KEY
EOF

echo ""
echo "==> Addresses written to $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Set DATABASE_URL, SOLVER_PRIVATE_KEY, AGENT_PRIVATE_KEY in $ENV_FILE"
echo "  2. Run indexer migrations: psql \$DATABASE_URL -f indexer/migrations/001_init.sql"
echo "  3. Start services with: source $ENV_FILE && cd indexer && node dist/index.js"
echo "  4. Verify at https://sepolia.basescan.org/address/$AGENT_REGISTRY"
